// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_AI_API_KEY: string
    NEXT_PUBLIC_AI_API_URL: string
  }
}

interface CloudflareEnv {
  DB: D1Database
}
